"""create countries

Revision ID: 0f62b346a3c9
Revises: 
Create Date: 2025-12-20 04:43:31.275871

"""
from alembic import op
import sqlalchemy as sa

revision = '0f62b346a3c9'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
