"""create projects

Revision ID: 406546b01842
Revises: 0f62b346a3c9
Create Date: 2025-12-20 08:18:03.970001

"""
from alembic import op
import sqlalchemy as sa

revision = '406546b01842'
down_revision = '0f62b346a3c9'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(length=60), nullable=True),
    sa.Column('stage', sa.String(length=40), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_country_id'), 'projects', ['country_id'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_kind'), 'projects', ['kind'], unique=False)
    op.create_index(op.f('ix_projects_sector'), 'projects', ['sector'], unique=False)
    op.create_index(op.f('ix_projects_stage'), 'projects', ['stage'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_stage'), table_name='projects')
    op.drop_index(op.f('ix_projects_sector'), table_name='projects')
    op.drop_index(op.f('ix_projects_kind'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_country_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
